name: Code Quality

on:
  pull_request:
  push:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Bun
      - uses: oven-sh/setup-bun@v1

      - name: Install front deps
        run: bun install

      - name: Type check (Vue)
        run: bun run vue-tsc --noEmit

      - name: Format - Front
        run: bun format:check

      - name: Lint
        run: bun lint:check

      # Rust
      - uses: dtolnay/rust-toolchain@stable

      - name: Format - Back
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check

      - name: Clippy
        run: cargo clippy --manifest-path src-tauri/Cargo.toml --all-targets -- -D warnings